apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverse
  #annotations:
  #  service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: "true"
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: reverse
  template:
    metadata:
      labels:
        app: reverse
    spec:
      containers:
      - name: reverse
        image: {{ .Values.version.reverse }}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
