apiVersion: v1
kind: Service
metadata:
  name: reverse
  annotations:
    #service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: "true"
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
  labels:
    app: reverse
spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy: Local
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: reverse
