apiVersion: v1
kind: Service
metadata:
  name: reverse
  labels:
    app: reverse
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: reverse
